# Generated by Django 4.2.2 on 2023-06-25 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Товарчик', max_length=20, verbose_name='Title')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 25, 18, 36, 29, 696645), verbose_name='Publsih date')),
                ('image', models.ImageField(default='images/1.jpeg', upload_to='images')),
            ],
        ),
    ]
